spring.application.name=user-service
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/user-service
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.hikari.schema=public
spring.jpa.hibernate.ddl-auto=update

#JWT
jwt.secret.key=qwertyuioplkjhgfdsazxcvbnmmnbvcxzasdfgytrewq
jwt.token.issuer=codeWithShehzab
