spring.application.name=gateway-service
#Service Discovery
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#Jwt
jwt.secret.key=qwertyuioplkjhgfdsazxcvbnmmnbvcxzasdfgytrewq
jwt.token.issuer=codeWithShehzab

#open endpoints
gateway.open-endpoints=/user/api/v1/ping,/user/api/v1/auth/login,/user/api/v1/auth/register
gateway.context.open-endpoints=/api/v1/ping,/api/v1/auth/login,/api/v1/auth/register
