spring.application.name=gateway-service
#Service Discovery
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#Jwt
jwt.secret.key=qwertyuioplkjhgfdsazxcvbnmmnbvcxzasdfgytrewq
jwt.token.issuer=codeWithShehzab
